### ISSUE TITLE
Some questions about your paper and code

### ISSUE THREAD

**Issue by ling718** [xumingze0308/ice-wacv2018#1]
I ran into some problems in reproducing your source code. Should this code be the result of modification after the publication of your paper? There are some differences between your code and your paper.  For example, the learnable parameters used in predicting the final result are not reflected in your code. In the comparison of the experimental results in the article, are you using the same 7 frames as before, or the 8 frames you mentioned in the article? May I ask what specific 8 frames of data? Is it the following 8 frames: 20140104_033, 20140104_037, 20140104_039, 20140104_043, 20140104_044, 20140104_045, 20140104_046, 20140104_047? I just use it for academic research experiments, and thank you very much for your help @xumingze0308

**Comment by xumingze0308** [comment]
This repo followed the model (C3D + RNN) in the WACV'18 paper, but used more data for both training and testing. For more details about the data, please refer here: https://github.com/xumingze0308/ice-WACV2018/tree/master/data
